# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: must_be 1.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "must_be".freeze
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["William Taysom".freeze]
  s.date = "2018-05-22"
  s.description = "must_be provides runtime assertions which can easily be disabled in production environments.  Likewise, the notifier can be customized to raise errors, log failure, enter the debugger, or anything else.".freeze
  s.email = "wtaysom@gmail.com".freeze
  s.extra_rdoc_files = [
    "ChangeLog.md",
    "README.md"
  ]
  s.files = [
    "ChangeLog.md",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "doc/readme/examples.rb",
    "doc/readme/run_examples.rb",
    "lib/must_be.rb",
    "lib/must_be/attr_typed.rb",
    "lib/must_be/basic.rb",
    "lib/must_be/containers.rb",
    "lib/must_be/containers_registered_classes.rb",
    "lib/must_be/core.rb",
    "lib/must_be/nonstandard_control_flow.rb",
    "lib/must_be/proxy.rb",
    "must_be.gemspec",
    "spec/must_be/attr_typed_spec.rb",
    "spec/must_be/basic_spec.rb",
    "spec/must_be/containers_spec.rb",
    "spec/must_be/core_spec.rb",
    "spec/must_be/nonstandard_control_flow_spec.rb",
    "spec/must_be/proxy_spec.rb",
    "spec/notify_matcher_spec.rb",
    "spec/spec_helper.rb",
    "spec/typical_usage_spec.rb"
  ]
  s.homepage = "http://github.com/wtaysom/must_be".freeze
  s.rubygems_version = "2.7.3".freeze
  s.summary = "must_be Runtime Assertions".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec-its>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 1.4"])
      s.add_development_dependency(%q<rspec-its>.freeze, ["~> 1.2"])
    else
      s.add_dependency(%q<rspec-its>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 1.4"])
      s.add_dependency(%q<rspec-its>.freeze, ["~> 1.2"])
    end
  else
    s.add_dependency(%q<rspec-its>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 1.4"])
    s.add_dependency(%q<rspec-its>.freeze, ["~> 1.2"])
  end
end

